### ISSUE TITLE
coverage 4.1b3 find_file_reporters does not set self.file_reporters

### ISSUE THREAD

**Issue by jasonm** [coveralls-clients/coveralls-python#108]
In coverage 4.0.x `Reporter.find_file_reporters` sets `self.file_reporters`: https://github.com/nedbat/coveragepy/blob/9099e41445d57295979526fb6cb1b924ff3fab36/coverage/report.py#L34-L50

In coverage 4.1b3 it just returns the value instead: https://github.com/nedbat/coveragepy/blob/7573494f3c3530ebbea383f6b07d364893eb0c57/coverage/report.py#L31-L49

So, when `CoverallsReporter` (which inherits the `Reporter` class referenced above) calls `find_file_reporters` and then looks for `self.file_reporters`, the latter is empty: https://github.com/coagulant/coveralls-python/blob/master/coveralls/reporter.py#L27-29

Not sure if this is an unintended API regression in `coverage` 4.1b3 or a newly introduced change that `coveralls-python` will have to update for.  cc @nedbat ?

Hope this report is helpful 😄 

cc @adriangoe for context.

**Comment by nedbat** [comment]
Thanks for testing with the latest Coverage.py.  The Reporter class is not a public API, so you are at risk of it changing out from under you like this.

**Comment by nedbat** [comment]
I would like to release coverage.py 4.1.  Will this cause a slew of bug reports?

**Comment by coagulant** [comment]
@nedbat I have not tested recent releases, if anyone is willing to provide a backward-compatible change, it would be awesome. 

Otherwise I can just make sure latest coveralls requires coverage < 4.1. Sorry, I'm not using coveralls anymore, so this package is not actively maintained by me.

**Comment by nedbat** [comment]
I've added back `file_reporters` with a deprecation warning.  Let me know if it helps, and in particular, if the deprecation warning is visible.

**Comment by TheKevJames** [comment]
@nedbat 

Hey! I'm the new maintainer for this project and I'm still getting myself fully up-to-speed. As far as I can tell, `coveralls-python` is working with the latest version of `coverage.py` by using `find_code_units` and `code_units` instead of `find_file_reporters` and `file_reporters` with [this ugly bit of fallback code](https://github.com/coveralls-clients/coveralls-python/blob/f14fbb4888582c31291fe8a30dd6605106a626e2/coveralls/reporter.py#L30-L40). If you happen to be keeping that around (but deprecated) on our account, you can feel free to remove it.

I'll close this issue, but don't hesitate to reach out. I would especially love to set up some system for running `coveralls-python` tests against to-be-released versions of `coverage.py`, if at all possible, to handle issues like this in the future -- if you have any ideas about that, please let me know!
