### ISSUE TITLE
How to use coveralls to include not tested modules in the code coverage report?

### ISSUE THREAD

**Issue by nbro** [coveralls-clients/coveralls-python#142]
So far I'm using `coveralls` to report the code coverage only from inside my "tests" folder, after the existing tests run. The problem with this is that not all modules have an associated unittest and thus are not reported by coveralls.

This is basically the script I'm using 

>https://github.com/nbro/ands/blob/master/scripts/travis.sh

in order to report the code coverage on Travis CI.

Is there a way to also include in the code coverage the modules which are still not tested? Because, so far, I've like 97% of code coverage, but this is of course misleading, since some modules are still not tested.

**Comment by TheKevJames** [comment]
Short answer: coverage reports are generated with [coverage.py](http://coverage.readthedocs.io/en/coverage-4.3.4/), this tool simply interprets the results and sends them along to coveralls. You're going to need to have coverage.py report the uncovered files to get the results you're looking for.

As far as I know, coverage.py can only create coverage data for files that are discovered by your test framework. A couple options you might play around with:
- Have your test framework import every files of your project, even if untested. From a quick look at your project, you may consider importing your algorithm files in the relevant `__init__.py` files and then having a test file which is simply `import ands`. No need to assert anything in your test, simply importing your library should let it find the right data. See [this link](http://mikegrouchy.com/blog/2012/05/be-pythonic-__init__py.html) for a bit more info (specifically: "What goes in `__init__.py`?). This is probably the Right Way™ to do this.
- Add files to the generated `.coverage` file manually. This is... not a good way to do things, but might be an easy hack. The `.coverage` files generated from coverage.py is effectively a json blob to which you could append the 0% coverage files. Again, this is probably not the right way to do things, but I'm including it since it came to mind.
