### ISSUE TITLE
Why do I need to specify the token for open-source projects?

### ISSUE THREAD

**Issue by mpenkov** [coveralls-clients/coveralls-python#223]
From [here](), it sounds like the token should _not_ be required:

> Note: public Travis-CI repos do not need this config file since Coveralls can get the information via their API (using access token exchange).

But if I don't specify the token, I get this error when running on Travis:

```
coveralls.exception.CoverallsException: Not on TravisCI. You have to provide either repo_token in .coveralls.yml or set the COVERALLS_REPO_TOKEN env var.
```

Our project is https://github.com/RaRe-Technologies/smart_open

**Comment by TheKevJames** [comment]
In order for us to detect that we're running in TravisCI (and process the job accordingly, eg. without a token), we need access to the `TRAVIS` environment variable -- it looks like your `tox.ini` file does not pass through the values we need here (since `tox` blacklists all environment variables by default). Adding the following to the relevant tox job config should do the trick:
```
passenv = TRAVIS TRAVIS_*
```

Please see [this page](https://coveralls-python.readthedocs.io/en/latest/usage/tox.html#usage-within-tox) in our documentation for more info!

**Comment by mpenkov** [comment]
Thank you for the reply!

May I suggest you put this information in your README? It's buried a little too deep for someone unfamiliar with coveralls.io and your particular project (I realize they're separate). Here's the path I took when looking for docs:

1.  https://docs.coveralls.io/ (has links to various languages)
2. https://docs.coveralls.io/python (has links to two projects, one of them yours, "Instructions in README’s.")
3. https://github.com/coveralls-clients/coveralls-python
4. Couldn't find any other helpful links to click, so went to https://github.com/coveralls-clients/coveralls-python/issues/new

A link from your README to https://coveralls-python.readthedocs.io would be helpful. The coveralls.io docs should probably point there too, as opposed to your github repo.

**Comment by TheKevJames** [comment]
@mpenkov good call! The bottom line of our README is
> For more information and usage instructions, see our [documentation](https://coveralls-python.readthedocs.io/en/latest/).

but that's definitely a bit small and hard to find. I'll make sure to highlight this a bit more (or feel free to submit a PR, if you're so inclined!).

Unfortunately, I don't have control over any of the coveralls.io docs directly; I'm not actually sure they keep that up to date and I see they link to all other project's Github repos instead of docs as well... ah well, just gives us an even better reason to make sure this is all included in the README directly!

**Comment by mpenkov** [comment]
> The bottom line of our README is

Wow, I totally missed that.

I'll make a PR.
